### ISSUE TITLE
ImportError: cannot import name 'ToolBox'

### ISSUE THREAD

**Issue by ppnman** [NUAA-AL/ALiPy#17]
我已经成功安装了alipy，用这个命令：`pip3 install alipy`.
但是当我运行`from alipy import ToolBox`，我收到了这个错误：`ImportError: cannot import name 'ToolBox'`
有人可以帮助我吗？我将无比感激。

**Comment by tangypnuaa** [comment]
您好，这个应该是没有将ToolBox变量加到__init__.py文件夹里的__all__变量造成的
您可以用Master分支下的代码更新工具包来解决这个问题

**Comment by ppnman** [comment]
好的，感谢。

**Comment by ppnman** [comment]
hi @tangypnuaa，我用手动编译的方式重新安装了最新的alipy。可还是有问题。
首先之前`from alipy import ToolBox`的报错仍然存在。
当我把那句话注释之后，后面又出现了新的问题。
```
Traceback (most recent call last):
  File "alipy.py", line 9, in <module>
    from alipy.index.multi_label_tools import get_Xy_in_multilabel
  File "/home/nvim/alipy.py", line 9, in <module>
    from alipy.index.multi_label_tools import get_Xy_in_multilabel
ImportError: No module named 'alipy.index'; 'alipy' is not a package
```

**Comment by tangypnuaa** [comment]
您好，我注意到您运行程序的文件也叫alipy，
`File "alipy.py", line 9`
可能是因为这个原因导致python没有导入到正确的alipy工具包，
请尝试换一个名字再试试

**Comment by ppnman** [comment]
> 您好，我注意到您运行程序的文件也叫alipy，
> `File "alipy.py", line 9`
> 可能是因为这个原因导致python没有导入到正确的alipy工具包，
> 请尝试换一个名字再试试

哇塞，真的是这个原因，非常感谢。
