### ISSUE TITLE
Possible bug in get_query_strategy inside toolbox.py

### ISSUE THREAD

**Issue by Arshita27** [NUAA-AL/ALiPy#3]
https://github.com/NUAA-AL/ALiPy/blob/71d716d2406c105556596f1e44442160d9a00d27/alipy/toolbox.py#L402-L409

When I tried to run ''QueryInstanceGraphDensity' it gave me an error: "Missing key 'train_idx' ", even when I was providing this key.

One possible bug could be that in line 402, kwargs.pop('train_idx', None) is being called which removes the train_idx key from the dictionary. Thus when it is called again in line 408, it gives an error as the key is no longer present due to the previous 'pop' statement. 

Do let me know if I am missing out anything.

**Comment by NUAA-AL** [comment]
Hi,

Thank you for your reporting, and we will fix this problem in the next release which will be published recently.
For now, please import the 'QueryInstanceGraphDensity' strategy independently for using it.
Here is an example:

from alipy.query_strategy.query_labels import QueryInstanceGraphDensity
density_strategy = QueryInstanceGraphDensity(X, y ,train_idx)
