### ISSUE TITLE
time.clock() has been removed from py38

### ISSUE THREAD

**Issue by luzhengli** [NUAA-AL/ALiPy#31]
“The function time.clock() has been removed, after having been deprecated since Python 3.3: use time.perf_counter() or time.process_time() instead, depending on your requirements, to have well-defined behavior. (Contributed by Matthias Bussonnier in bpo-36895.)”

**Comment by lukekolbe** [comment]
This has already in the latest release, no?
[See change log](https://github.com/NUAA-AL/ALiPy/commit/57f5a1e4c0252436ecf2572da6973d054807add5)
