### ISSUE TITLE
Problem with QueryInstanceCoresetGreedy and other strategies that take train_idx argument

### ISSUE THREAD

**Issue by lukekolbe** [NUAA-AL/ALiPy#32]
This error can be easily replicated by running the example in examples/AL_settings/query_instance.py
If you change the batch size to 10, you'll get an error. Here, it's an IndexError (see below), in my own application I get an Assertion Error. Regardless of error type, it's always caused by the  assert self.train_idx[ind] in unlabel_index line that several query strategies use (those that take train_idx as argument). It's strange because the select method of the QueryInstanceCoresetGreedy class has a batch_size argument with default 1, so it should take batches...

`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-1-8fe4f5b96bb7> in <module>
     96     eer_result.append(copy.deepcopy(main_loop(alibox, eer, round)))
     97     rnd_result.append(copy.deepcopy(main_loop(alibox, rnd, round)))
---> 98     cors_result.append(copy.deepcopy(main_loop(alibox, cors, round)))
     99     dw_result.append(copy.deepcopy(main_loop(alibox, dw, round)))
    100     quire_result.append(copy.deepcopy(main_loop(alibox, quire, round)))

<ipython-input-1-8fe4f5b96bb7> in main_loop(alibox, strategy, round)
     39         # Select a subset of Uind according to the query strategy
     40         # Passing model=None to use the default model for evaluating the committees' disagreement
---> 41         select_ind = strategy.select(label_index=label_ind, unlabel_index=unlab_ind, batch_size=10, model=model)
     42         label_ind.update(select_ind)
     43         unlab_ind.difference_update(select_ind)

~/anaconda3/lib/python3.8/site-packages/alipy/query_strategy/query_labels.py in select(self, label_index, unlabel_index, batch_size, **kwargs)
   1877             # should have min_distance of zero to a cluster center.
   1878             assert ind not in self.already_selected
-> 1879             assert self.train_idx[ind] in unlabel_index
   1880 
   1881             self.update_distances([ind], only_new=True, reset_dist=False)

IndexError: index 1250 is out of bounds for axis 0 with size 350`

**Comment by tangypnuaa** [comment]
Hi, thank you for reporting this problem.
I have fixed it in the main branch. Please pull the latest version.
