### ISSUE TITLE
二分类index error问题

### ISSUE THREAD

**Issue by zhaollj** [NUAA-AL/ALiPy#38]
<img width="288" alt="1" src="https://user-images.githubusercontent.com/48301843/224627096-503a892e-8fbc-476c-b6ab-f78cab84a703.PNG">
<img width="362" alt="2" src="https://user-images.githubusercontent.com/48301843/224627126-fa3259ef-aac5-4af6-b2ec-5b3bced776d1.PNG">
<img width="374" alt="3" src="https://user-images.githubusercontent.com/48301843/224627150-62d0e903-76e8-40f4-8975-773be79e0245.PNG">
<img width="336" alt="4" src="https://user-images.githubusercontent.com/48301843/224627173-1fca44eb-fd45-4671-8f01-d0c6f6738aa4.PNG">
您好！我在进行二分类，可以确定输入的x和y都是没有问题的，请问为什么会出现index error呢？还有就是这个41712是在哪里出现的呢？

**Comment by tangypnuaa** [comment]
您好，可以提供下使用的alipy版本吗？如果可能也请提供下代码和数据方便我们复现问题，谢谢

**Comment by zhaollj** [comment]
使用的是alipy 1.2.5，代码和数据发您了，谢谢！
[testcode.zip](https://github.com/NUAA-AL/ALiPy/files/10974923/testcode.zip)

**Comment by tangypnuaa** [comment]
我尝试运行了您的代码，没有出现问题。我建议您试试把代码目录下train_idx.txt, unlabel_idx.txt, test_idx.txt, label_idx.txt四个文件删除或改名再试试看。这可能是改了数据集而没有重新划分数据的原因，alipy检测到当前目录存在划分文件，所以读取了现有的数据划分而没有重新划分导致出错（这本来会输出warning信息，但是代码开头抑制了warning输出）

**Comment by zhaollj** [comment]
我把之前相关的文件删除了，问题解决了，谢谢您！这个问题困扰了好久了
