### ISSUE TITLE
Possible bug in get_query_strategy/query_labels.py

### ISSUE THREAD

**Issue by ztono** [NUAA-AL/ALiPy#4]
In class "QueryInstanceQUIRE" there is a function named "select" and an argument of it is batch_size. But I found the argument doesn't really have an effect on the result. If the batch_size is less than the number of unlabeled items, the number of function output will always be 1.

**Comment by tangypnuaa** [comment]
Hi ztono!

QUIRE is not a batch mode active learning algorithm, it will only select one instance for querying at each iteration.  So the batch size is always 1. However, we keep this parameter to ensure the api of all strategies the same.

We will consider to delete this parameter and use **kwargs instead.

Thank you for your report.
