### ISSUE TITLE
更换数据集之后，运行出问题

### ISSUE THREAD

**Issue by ppnman** [NUAA-AL/ALiPy#7]
您好，非常感谢Alipy的伟大工作，这是我见过的最全面的主动学习包。
在我准备运行[AL for multi-label data](http://parnec.nuaa.edu.cn/huangsj/alipy/example.html)示例代码的时候出了问题。
用`iris`数据集是可以运行的，但是当我换了一个数据集就没法运行了。
我现在的代码是这样的
```
dataset_filepath = os.path.join(
    os.path.dirname(os.path.realpath(__file__)), 'scene')

X, mult_y = import_libsvm_sparse(dataset_filepath, True).format_sklearn()
mult_y[mult_y == 0] = -1

# X, y = load_iris(return_X_y=True)
# mlb = OneHotEncoder()
# mult_y = mlb.fit_transform(y.reshape((-1, 1)))
# mult_y = np.asarray(mult_y.todense())
# mult_y[mult_y == 0] = -1

alibox = ToolBox(X=X, y=mult_y, query_type='PartLabels')
alibox.split_AL(test_ratio=0.2, initial_label_rate=0.05, all_class=False)


def main_loop(alibox, round, strategy):
    train_idx, test_idx, label_ind, unlab_ind = alibox.get_split(round)
    # Get intermediate results saver for one fold experiment
    saver = alibox.get_stateio(round)
    # base model
    model = LabelRankingModel()

    while len(label_ind) <= 120:
        # query and update
        select_labs = strategy.select(label_ind, unlab_ind)
        # use cost to record the amount of queried instance-label pairs
        if len(select_labs[0]) == 1:
            cost = mult_y.shape[1]
        else:
            cost = len(select_labs)
        label_ind.update(select_labs)
        unlab_ind.difference_update(select_labs)

        # train/test
        X_tr, y_tr, _ = get_Xy_in_multilabel(label_ind, X=X, y=mult_y)
        model.fit(X=X_tr, y=y_tr)
        pres, pred = model.predict(X[test_idx])
        perf = alibox.calc_performance_metric(y_true=mult_y[test_idx], y_pred=pred, performance_metric='hamming_loss')

        # save
        st = alibox.State(select_index=select_labs, performance=perf, cost=cost)
        saver.add_state(st)

    return copy.deepcopy(saver)


audi_result = []
quire_result = []
random_result = []
mmc_result = []
adaptive_result = []

for round in range(5):
    # init strategies
    audi = QueryMultiLabelAUDI(X, mult_y)
    quire = QueryMultiLabelQUIRE(X, mult_y)
    mmc = QueryMultiLabelMMC(X, mult_y)
    adaptive = QueryMultiLabelAdaptive(X, mult_y)
    random = QueryMultiLabelRandom()

    audi_result.append(main_loop(alibox, round, strategy=audi))
    quire_result.append(main_loop(alibox, round, strategy=quire))
    mmc_result.append(main_loop(alibox, round, strategy=mmc))
    adaptive_result.append(main_loop(alibox, round, strategy=adaptive))
    random_result.append(main_loop(alibox, round, strategy=random))

analyser = alibox.get_experiment_analyser(x_axis='cost')
analyser.add_method(method_name='AUDI', method_results=audi_result)
analyser.add_method(method_name='QUIRE', method_results=quire_result)
analyser.add_method(method_name='RANDOM', method_results=random_result)
analyser.add_method(method_name='MMC', method_results=mmc_result)
analyser.add_method(method_name='Adaptive', method_results=adaptive_result)
analyser.plot_learning_curves()

```
可以看到我的代码和示例代码的唯一区别就是我更改了数据源`X`和`mult_y`
`X`是一个`2407*294`维的`ndarray`, `mult_y`是一个`2407*6`的`ndarray`。
X是样本特征集合，mult_y是标签集合。
`mult_y`如下
```
array([[ 1, -1, -1, -1,  1, -1],                            
[ 1, -1, -1, -1, -1,  1],                            
[ 1, -1, -1, -1, -1, -1],                            
 ...,
[-1, -1, -1, -1, -1,  1],                            
[-1, -1, -1, -1, -1,  1],                            
[-1, -1, -1, -1, -1,  1]])
```
`X`如下
```
array([[0.646467  , 0.666435  , 0.685047  , ..., 0.247298  ,
0.0140249 , 0.0297093 ],
[0.770156  , 0.767255  , 0.761053  , ..., 0.137833  ,
0.0826722 ,0.0363203 ],
[0.793984  , 0.772096  , 0.76182   , ..., 0.0511252 ,
0.112506 ,0.0839236 ],
 ...,
[0.952281  , 0.944987  , 0.905556  , ..., 0.0319002 ,
0.0175471 ,0.0197344 ]])

```
我的数据格式是符合Alipy的规范的，为什么运行会报错：
`ValueError: cannot reshape array of size 0 into shape (0, newaxis)`

**Comment by ppnman** [comment]
原来是这一行限制了已标记数据的个数
`while len(label_ind) <= 120:`

**Comment by ppnman** [comment]
上面那个问题解决之后，又碰到了一个新的问题。
如果`X`是`150*295`，`mult_y`是`150*6`，算法可以正常进行。
但如果`X`是`2407*295`，`mult_y`是`2407*6`，算法在
`quire_result.append(main_loop(alibox, round, strategy=quire))`这一步会卡死。
显示`[1]    123231 killed     python3 demo.py`
难道Alipy不能运行太大的数据集吗？

**Comment by ppnman** [comment]
> 上面那个问题解决之后，又碰到了一个新的问题。
> 
> 1. 如果`X`的维度是`150*295`，`mult_y`的维度是`150*6`，算法可以正常进行。
> 2. 如果`X`的维度是`2407*295`，`mult_y`的维度是`2407*6`，算法在
>    `quire_result.append(main_loop(alibox, round, strategy=quire))`这一步会运行很久，然后进程被系统杀死。终端显示`[1]    123231 killed     python3 demo.py`
> 
> 难道Alipy不能运行太大的数据集吗？

debug发现是在`alipy/query_strategy/multi_label.py`的445行卡死，但不知道原因。

**Comment by tangypnuaa** [comment]
您好！

程序的时间与空间复杂度取决于不同的查询算法。QUIRE方法需要进行多次N阶矩阵求逆/伪逆运算，其中N为您的数据集大小，并需要存储中间变量，时间和空间复杂度都比较高。445行是在对一个len(unlabeled_data)阶的矩阵求伪逆，卡死有可能是因为MemoryError引起的。您可以尝试使用[Large Scale Active Learning](http://parnec.nuaa.edu.cn/huangsj/alipy/page_adv/special_settings_large_scale.html)中的策略，先从未标记集合中采样一个子集，再从子集中选样本查询。

我们也会再测试检查一下这部分的代码，看看是否有其他原因。请关注dev分支的更新以在第一时间收到最新的bug修复补丁。感谢您汇报这个问题。

**Comment by ppnman** [comment]
> 您好！
> 
> 程序的时间与空间复杂度取决于不同的查询算法。QUIRE方法需要进行多次N阶矩阵求逆/伪逆运算，其中N为您的数据集大小，并需要存储中间变量，时间和空间复杂度都比较高。445行是在对一个len(unlabeled_data)阶的矩阵求伪逆，卡死有可能是因为MemoryError引起的。您可以尝试使用[Large Scale Active Learning](http://parnec.nuaa.edu.cn/huangsj/alipy/page_adv/special_settings_large_scale.html)中的策略，先从未标记集合中采样一个子集，再从子集中选样本查询。
> 
> 我们也会再测试检查一下这部分的代码，看看是否有其他原因。请关注dev分支的更新以在第一时间收到最新的bug修复补丁。感谢您汇报这个问题。

感谢您的解答！
之前出现那个问题所使用的数据集是：[Libsvm Dataset](https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/multilabel.html#mediamill%20(exp1))
我现在尝试下Large Scale Active Learning，就先关闭这个issue了。
