### ISSUE TITLE
会考虑支持更多的多标签主动学习算法吗

### ISSUE THREAD

**Issue by ppnman** [NUAA-AL/ALiPy#8]
首先感谢Alipy开发者的工作给我们这些使用者减轻了很多的负担，但我目前发现Alipy在多标签主动学习方面的算法都不是很新。
Alipy目前支持QUIRE(2014), AUDI(2013), MMC(2009), ADAPTIVE(2013)等算法。
会考虑支持更多优秀的多标签主动学习算法吗？比如2DAL等等。
还是因为没有实现的那些算法在性能上和这四个相比没有足够的提升，所以暂时不需要实现它们？

**Comment by tangypnuaa** [comment]
您好，感谢您对我们工作的认可。ALiPy会在后续的更新中加入更多的查询算法。

**Comment by ppnman** [comment]
了解了，谢谢回复！
